### ISSUE TITLE
Error in puppeth command

### ISSUE THREAD

**Issue by danielksan81** [amissine/ethereumIsFun#2]
The current used format and indata are incompatible with the current version of puppeth corresponding to the geth version 1.7.3-stable.
In the current peth file line 51 % 52 should be
```
format+='\n\n%s\n%s\n\n'
indata+=' 2 2'
```

**Comment by amissine** [comment]
This kind of discrepancy creeps in sooner or later... :) I am not focused on this project at the moment, feel free to fork and fix. And thank you!
